-- +goose Up
CREATE TABLE IF NOT EXISTS todos(
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  IS_COMPLETE BOOLEAN,
  CREATED_AT TIMESTAMPTZ DEFAULT now(),
  UPDATED_AT TIMESTAMPTZ DEFAULT now()
);
-- +goose Down
DROP TABLE IF EXISTS todos;
